from math import pi

LEFT_MOTOR_PORT = 'outA'
RIGHT_MOTOR_PORT = 'outB'

ROBOT_RADIUS_MM = 70

WHEEL_RADIUS_MM = 15
WHEEL_CIRCUMFERENCE_MM = 2 * pi * WHEEL_RADIUS_MM
WHEEL_COUNTS_PER_ROT = 360

AXIS_RADIUS_MM = 50
AXIS_DIAMETER_MM = 50
AXIS_CIRCUMFERENCE_MM = 2 * pi * AXIS_RADIUS_MM
